### ISSUE TITLE
openssl < 1:1.0.1-0.3.beta3 is obsoleted

### ISSUE THREAD

**Issue by lewki** [philyuchkoff/openssl-RPM-Builder#1]
building already, but when i install package failed dependencies with openssl-libs

# rpm -ivh /root/rpmbuild/RPMS/x86_64/openssl-1.1.1g-1.el7.x86_64.rpm
error: Failed dependencies:
	openssl < 1:1.0.1-0.3.beta3 is obsoleted by (installed) openssl-libs-1:1.0.2k-12.el7.x86_64

**Comment by philyuchkoff** [comment]
@lewki 
Try to install like this:
`rpm -ivvh /root/rpmbuild/RPMS/x86_64/openssl-1.1.1h-1.el7.x86_64.rpm --nodeps`

I haven't figured out how to fix it yet :(
