### ISSUE TITLE
openssl-libs build?

### ISSUE THREAD

**Issue by vnngoanhtuan** [philyuchkoff/openssl-RPM-Builder#7]
Hi,

Can you guideline how to build openssl include openssl-libs?

Thanks,
Tuan Ngo

**Comment by kerneltravel** [comment]
not resolved,too.

**Comment by philyuchkoff** [comment]
@vnngoanhtuan 
@kerneltravel 
Take a look please [https://wiki.openssl.org/index.php/Compilation_and_Installation](https://wiki.openssl.org/index.php/Compilation_and_Installation) - maybe there is information you need here.
