### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Amos20191021** [philyuchkoff/openssl-RPM-Builder#8]
Ur original code ：

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
%files
%{openssldir}
%defattr(-,root,root)

%files devel
%{openssldir}/include/*
%defattr(-,root,root)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I modified as follows：

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
%files
                  %{openssldir}
                  %defattr(-,root,root)
                  /usr/bin/openssl
                  /usr/lib64/libcrypto.so.1.1
                  /usr/lib64/libssl.so.1.1

                  %files devel
                   %{openssldir}/include/*
                   %defattr(-,root,root)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by philyuchkoff** [comment]
[Amos20191021](https://github.com/Amos20191021)
Thank you!
