### ISSUE TITLE
编译后的rpm，安装完后 yum update 无法运行，求解

### ISSUE THREAD

**Issue by coffeepepsi** [philyuchkoff/openssl-RPM-Builder#9]
[root@centos2207 ~]# yum update
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
正在解决依赖关系
--> 正在检查事务
---> 软件包 openssl.x86_64.0.3.0.8-1.el7 将被 升级
---> 软件包 openssl.x86_64.1.1.0.2k-25.el7_9 将被 更新
Removing openssl.x86_64 0:3.0.8-1.el7 - ud due to obsoletes from installed 1:openssl-libs-1.0.2k-25.el7_9.x86_64
--> 正在使用新的信息重新解决依赖关系
--> 正在检查事务
---> 软件包 openssl.x86_64.0.3.0.8-1.el7 将被 升级
--> 解决依赖关系完成
错误： Multilib version problems found. This often means that the root
      cause is something else and multilib version checking is just
      pointing out that there is a problem. Eg.:
      
        1. You have an upgrade for openssl which is missing some
           dependency that another package requires. Yum is trying to
           solve this by installing an older version of openssl of the
           different architecture. If you exclude the bad architecture
           yum will tell you what the root cause is (which package
           requires what). You can try redoing the upgrade with
           --exclude openssl.otherarch ... this should give you an error
           message showing the root cause of the problem.
      
        2. You have multiple architectures of openssl installed, but
           yum can only see an upgrade for one of those architectures.
           If you don't want/need both architectures anymore then you
           can remove the one with the missing update and everything
           will work.
      
        3. You have duplicate versions of openssl installed already.
           You can use "yum check" to get yum show these errors.
      
      ...you can also use --setopt=protected_multilib=false to remove
      this checking, however this is almost never the correct thing to
      do as something else is very likely to go wrong (often causing
      much more problems).
      
      保护多库版本：1:openssl-1.0.2k-25.el7_9.x86_64 != openssl-3.0.8-1.el7.x86_64

源码编译 openssl 则正常

**Comment by philyuchkoff** [comment]
Can you try remove old versions:
```
rpm -qa | grep openssl
rpm -e --justdb --nodeps <yourpackage>
```
